spring.application.name=aakil-skin-hub

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/aakil_skin_hub?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${arif6397}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT: Correct Hibernate dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Server
# ===============================
server.port=8081